# Generated by Django 2.0.7 on 2018-08-03 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_auto_20180727_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='recommendations',
            field=models.ManyToManyField(blank=True, related_name='recommendations', to='stories.Author'),
        ),
    ]
