# Generated by Django 2.0.7 on 2018-08-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_auto_20180802_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
