# Generated by Django 2.0.7 on 2019-01-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_auto_20190107_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
