# Generated by Django 2.0.10 on 2019-02-26 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_auto_20190107_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='username',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
