branch-defaults:
  master:
    environment: story-board-dev
environment-defaults:
  story-board-dev:
    branch: null
    repository: null
global:
  application_name: story_board
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.4
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
